### ISSUE TITLE
Minecraft Crash beim minen.

### ISSUE THREAD

**Issue by ECLInstamash** [ruyanve/The-Built#7]
[crash-2017-04-27_18.57.25-client.txt](https://github.com/ruyanve/Adventure/files/962318/crash-2017-04-27_18.57.25-client.txt)

**Comment by ruyanve** [comment]
Known crash with item tooltips, under investigation

**Comment by ruyanve** [comment]
Minetweaker compat issue, temporary fixed by disabling minetweaker
